### PR TITLE
Removed skotos.net links and obsolete www files

### PR DESCRIPTION
**Pull request by saraht45**
**Updated skoot/usr/HTTP/sys/httpd.c**

Removed functions with skotos.net references. These functions are not used anywhere in SkotOS.
- query_http_cc_document
- query_http_create_document
- query_http_tos_document
- query_http_address_document
- query_http_youth_document 
- query_http_tooyoung_document
- query_http_waiver_document

**Removed files in the skoot/usr/HTTP/data/www/ directory**
**Removed files in the skoot/usr/Theatre/data/www/ directory**
**Removed files in the skoot/usr/TextIF/data/www/ directory**

These files are old SAM files used for logging in, changing passwords, etc. We now use different systems to accomplish these tasks. Also removed old client files (java and Flash).

### CODE REVIEW

**Comment by noahgibbs** [comment]
Ooh! I'd been looking at that usr/HTTP/data/www directory with the ancient client files, but I wasn't 100% sure. Great find.

**Comment by noahgibbs** [comment]
Hm. You changed it to say query_portbase in the HTTP connection... But the portbase is just a number (10000 in this case.) That's not what you want here...

**Comment by noahgibbs** [comment]
Query_hostname is a definitely improvement. But we talked about adding an entry in skoot/usr/System/data/instance for the login server (e.g. rwot-login.testing-8.madrubyscience.com) - the "hostname" string is usually for the game server (e.g. rwot.testing-8.madrubyscience.com). I *think* that's still going to be necessary here.

**Comment by noahgibbs** [comment]
Also we may still need the TOS document.

**Comment by saraht45** [comment]
Yeah, I added a login_url setting in instance but forgot to copy those changes over to the Skotos/skoot directory before committing. Oops. I have those changes ready now. Should I submit a new PR?

**Comment by saraht45** [comment]
Also, the TOS document is still there but I removed the query_tos_document reference as it was never being used.

**Comment by ChristopherA** [comment]
There are ways to modify an existing PR, but requires some more complex git fu. Thus it is fine to submit a new one, and close this one, but do mention this closed PR in the new one in case someone in the future wants to connect it to the conversation.

**Comment by noahgibbs** [comment]
When you push commits to the branch, it adds them to the PR. So the one you pushed is now shown as part of this change. Which looks fine to me, so I don't think you need to close this and open a new one.

**Comment by noahgibbs** [comment]
TOS is still used. If you go to skoot/usr/HTTP/obj/httpconn.c and search for TOS you'll see a thing that calls query_document("tos"), which winds up calling query_http_tos_document(). And thin-auth can still return the TOS error.

**Comment by saraht45** [comment]
Ah, okay. I just did a search for query_http_tos_document. Looking at httpconn.c, I see references to other links I removed. Youth and unpaid we want to keep but point to thinauth?

**Comment by noahgibbs** [comment]
Unpaid we can point at thin-auth. Youth can go - it turns out thin-auth will never return the code that would trigger it.

**Comment by saraht45** [comment]
What about address? Will that ever be needed for billing purposes?

**Comment by noahgibbs** [comment]
Mostly this looks good. The problem I see at the moment is that login_url has the default "localhost", but you're making the URL by just appending "/login.php" -- there's no https.

I would suggest renaming "login_url" to "login_hostname" (since localhost is a hostname, not a URL) and adding an https in front in query_login_document(). Once you've done that and the same for the TOS and CC documents (append https) then I think this looks great and I'm happy to merge it.

**Comment by noahgibbs** [comment]
Cool. I'm testing with this locally by patching the gables_game dgd.manifest to use your branch and then doing a full restart (shutdown, rm skotos.database, restart.) Looks like login_url didn't get corrected to login_hostname in the variables-and-data section of usr/System/initd.c, and also when parsing the variable (do a search for login_url and update it where you see it.) Once those are fixed, this compiles and boots for me.

You can check your work with a full cold-boot (yeah, I know, takes forever :-( ). But you can also log in on the wiztool port and compile the file:

~~~
Noahs-MBP-2:gables_game noah$ telnet localhost 10098
Trying ::1...
Connected to localhost.
Escape character is '^]'.

Welcome to SkotOS.

What is your name: bobo
Password:
> cd /usr/System/
/usr/System
> compile initd.c
$0 = </usr/System/initd>
>
~~~

Of course, this will only work after a proper boot-up... If the login server isn't running then the wiztool port won't let you in. But if you start with a bootable DGD and then make changes, you can repeatedly compile the file quite quickly, which is great for debugging.

**Pull request merged**
