### PR TITLE
Terminal and iterm fixes

### PR DESCRIPTION
**Pull request by noahgibbs**
Add and use a new_terminal.sh script to open a new terminal window in a terminal-aware way. Get rid of an old unused script meant to do the same. And fix a comment in an example script that should probably be removed soon.

### CODE REVIEW

**Comment by ChristopherA** [comment]
@saraht45 This looks like a good first one for you to approve and merge PR.

Basically first checkout this PR locally. 

I personally find the GitHub command line app `gh` (installed with `brew install gh`  the easiest.

In your copy of the SkotOS folder `gh pr checkout 63 --repo ChatTheatre/Skotos` to load Noah's PR , then make sure it works for you.

If it does, then go to the Github web page for this PR and  then under the "Files Changed" tab you'll see a "Review Changes" button. Click on the Approved Button, type in "tACK" (acronym for tested acknowledge) and any comments you have "tACK - tested on my MacBook Pro using macOS Big Sur 11.3. Open terminal correctly". Click OK, and you'll be back at the Comments and Merge Page, and click Merge twice.

**Comment by noahgibbs** [comment]
For this change, I'd actually recommend a slightly different way to test locally:

In gables_game:

* run "bundle install" to get the latest dgd-tools
* modify dgd.manifest to point to the terminal_and_iterm branch of noahgibbs/SkotOS
* run "dgd-manifest update" so that the .root directory and local SkotOS clone contain the right files
* run deploy_scripts/mac/setup.sh with at least your terminal of choice - it works for me in both Apple Terminal and iTerm2

 With these instructions you're testing locally by pointing an app at this branch as its library rather than testing the library directly.

**Comment by saraht45** [comment]
@noahgibbs 

I followed the instructions and while it seemed like the commands worked, the files did not update in deploy_scripts, and the new files that should be there are not. This is what I have in my dgd.manifest file.

            "git": {
                "url": "https://github.com/noahgibbs/SkotOS.git",
                "branch": "terminal_and_iterm_fixes"
            },

With Chris' method, SkotOS was updated, and a terminal was opened which means your code update works (but we know the basic SkotOS setup doesn't work).

**Comment by saraht45** [comment]
I deleted the Skotos repo on my computer and cloned it again (did not do setup). Then went back to gables_game and walked through the steps again. It worked that time and the log terminal appears after setup.

**Review by saraht45 — APPROVED** [review]
tACK - tested on my MacBook Pro using macOS Mojave 10.14.6. Opened terminal correctly.

**Pull request merged**
