### PR TITLE
Suspend rewritten

### PR DESCRIPTION
**Pull request by saraht45**
Merryized the !suspend/+suspend commands. Had to update skoot/usr/UserAPI/sys/udatd.c to allow access to udat suspend functions from Merry.

### CODE REVIEW

**Comment by noahgibbs** [comment]
This looks good. One thing I might add: when calling obj/udat and/or sys/udatd's set_suspended functions, it would be good to do logging or otherwise record it. Right now if you can call from DGD, you can suspend/unsuspend without any record being kept.

That's not a bug you added, but it would be good to fix.

**Comment by saraht45** [comment]
It does get logged at the Merry level via the assist system. Is it better to log at the DGD level?

**Comment by saraht45** [comment]
I looked up the old DGD suspend code and found this line:

	    LOGD->add_entry("Suspend Log",
			    describe_one(body) + "[" +
			    user->query_name() + "] unsuspended " +
			    name + "'s account",
			    name +
			    "'s account is no longer suspended for this game.\n");


Is this what you mean by logging?

**Comment by noahgibbs** [comment]
Yup, that'll work. There are also macros (#defines) with names like WARNING and INFO that will work in System/log.h if you #include it.

**Comment by saraht45** [comment]
Awesome. Thanks for the direction!

What are some other situations where we might want to log at the DGD level?

**Comment by noahgibbs** [comment]
Anything that people are likely to consider unfair, lie about, or otherwise treat as sensitive is at least fair game. In addition to bans/suspensions, obvious candidates include stuff like adding story points. I don't *think* you can change the auth server info any more (e.g. make somebody an admin on the game) from the DGD side any more, though that would certainly be something to log if you could.

**Comment by noahgibbs** [comment]
It would be fair to say "don't log anything if it's just a DGD interface" since in some sense we're always 100% vulnerable to people who can touch the wizard interface. But it's nice to at least have a few tripwires as a reminder that folks should play nice and be basically honest ;-)

**Comment by shentino** [comment]
:)

**Comment by saraht45** [comment]
> It would be fair to say "don't log anything if it's just a DGD interface" since in some sense we're always 100% vulnerable to people who can touch the wizard interface. But it's nice to at least have a few tripwires as a reminder that folks should play nice and be basically honest ;-)

Makes perfect sense :)

The code has been updated to include the logging.

**Pull request merged**
