### PR TITLE
Dgd plus commands removed

### PR DESCRIPTION
**Pull request by saraht45**
**Removed the following broken or obsolete DGD +commands.**
    +use
    +statistics
    +snoop
    +setpass
    +drag
    +echo
    +echoall
    +erasescript
    +heal
    +log
    +make
    +npc
    +partition
    +scripts
    +refresh
    +ren
    +ren_ip
    +resetprops
    +resetpropsandclear
    +list

**Removed the following DGD +commands that have already been Merryized**
    +skills
    +whereis
    +inventory
    +woe
    +whois
    +who
    +customers
    +staff
    +people
    +busy
    +info
    +roster
    +users
    +setprop
    +spawn
    +goto
    +join
    +grab
    +ungrab
    +rename

**The following DGD +commands should be Merryized and then removed**
    +emote
    +summon
    +unsummon
    +emit
    +emitall
    +stat
    +obstat
    +broadcast
    +slay
    +transfer
    +lock
    +unlock
    +grab
    +ungrab

### CODE REVIEW

**Comment by noahgibbs** [comment]
In general, this looks great.

If we remove setprop and statistics from the CtlD API here, do we also need to remove it from thin-auth? Because right now, thin-auth still has setprop (https://github.com/ChatTheatre/thin-auth/blob/master/server-control.php#L480), though it returns "deprecated" for statistics.

**Comment by saraht45** [comment]
Hmmm... I maybe should not have removed it from thin auth. There is no easy way to test it without deploying a server online so I'll make a note to not touch anything in that directory.

**Comment by noahgibbs** [comment]
The one I'm looking at is skoot/usr/UserAPI/lib/ctlapi.c - and I think that's to send a CtlD command. But I don't know enough to be sure what setprop is used for in that context. I'd have to read code and infer.

**Comment by ChristopherA** [comment]
I’ve talked with @jandrieu about maybe having @saraht45 start diving into ThinAuth and SkotOS to limit or remove some logging & other extras. In particular minimizing or eliminating GDPR or CA personal data in SkotOS itself. 

Advantages are having learn about lower levels of SkotOS, also learn how to support ThinAuth bugs, and maybe a better base to work toward a better auth framework like Oauth someday.

**Comment by noahgibbs** [comment]
Certainly it could be reasonable to have Sarah look into this and whether setprop is still used there. It's *able* to be used, but I'm not sure it *is* used. I think there are logs that would show that.

The statistics command is no longer used or useful and Sarah could probably remove it without any great trouble. The hard part of setprop is just determining whether it needs to go or not.

**Comment by noahgibbs** [comment]
Hm, no, looks like setprop is still usable and (I think) like we should *not* remove it. Statistics could go, though.

**Comment by saraht45** [comment]
I'm happy to look into ThinAuth. How it communicates with SkotOS is still a mystery to me but something that I will definitely need to figure out in order for account info to be stored in woe. Maybe that's where setprop comes into play?

But for the purpose of this PR I will restore the ctlapi.c and related files since the objective is only to remove dgd level commands.

**Comment by noahgibbs** [comment]
Sounds good. We can talk more about thin-auth when you like, if that's useful.

**Comment by saraht45** [comment]
> Sounds good. We can talk more about thin-auth when you like, if that's useful.

That would be very useful :) I'll reach out to set something up.

**Comment by saraht45** [comment]
ctlapi.c has been restored

**Pull request merged**
